### ISSUE TITLE
random paint recoloring

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#1047]
### Short Description of the issue:
Upon loading the game all entities will have random sections of discolored blocks. This happens every time and is completely random as to what blocks change color. 
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
okay thats a weird one, I cant reproduce obviously... I will dig further and keep you posted. Thanks!

**Comment by pinesh** [comment]
seems to happen if you load a pre paint painted ship with some default stuff

**Comment by tsunamayo** [comment]
Not sure if it was the same bug but I fixed a similar one. I will push a new build today, could you please tell me if its still bugging after that? Thanks!

**Comment by Tomatart** [comment]
I will.

**Comment by tsunamayo** [comment]
Thanks! Actually the new build just finished uploaded. Cheers!

**Comment by Tomatart** [comment]
I am still experiencing entities having the paint colors change randomly when reloading the game. I would like to add that the mis-coloring only appears in light. as seen in this image 
![screenshot 358](https://user-images.githubusercontent.com/26846110/50367842-e253e580-0537-11e9-8bf1-3df66c06a83d.png)
the area illuminated by the headlamp is a red color (the random color that appeared on this reload) while the un-lit areas in the peripheral vision appears as the original grey colors I painted them as.

**Comment by tsunamayo** [comment]
This issue is deprecated as custom paint are removed sadly =( Thanks!
