### ISSUE TITLE
[Bug] Double Q for paint

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1370]
When selecting the paint tool and the specific paint color, you have to press Q/click twice. Thanks for coming to my TED talk

**Comment by tsunamayo** [comment]
You mean to open the paint selection window? I only have to click once on my side... Any specific think you might be doing? What is your mapping? Thanks

**Comment by ZachZent** [comment]
Ok that's weird. I reset the game and it is fixed, BUT I know this is not just me. Aiwi [Koivoi] on Discord confirmed he has the same issue. I will see if this happens again

**Comment by tsunamayo** [comment]
gotcha, if you have any hint or a log file dont hesitate. I will try to think on what could cause that. When it start to happens it happens all the time or just randomly?

**Comment by ZachZent** [comment]
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3405378/output_log.txt)

Here is the output log. I shall keep testing as I update my exploration ship

**Comment by Majikmonster** [comment]
I have had to double click paint colors in the UI to get the window to close, but I can also single click and exit the UI with Q and still have the proper paint selected.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3408842/output_log.txt)
Hope this helps!

**Comment by tsunamayo** [comment]
Okay I think this issue should be fixed, but as I was not able to reproduce all the time I am not 100% sure. If it you encounter it again please book another issue! Cheers
